name: Release ACAI SDK

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - main


jobs:
  archive-release:
  #timeout-minutes: 10 # timeout for the job
    name: Archive package and release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file
      uses: canastro/copy-file-action@master
      with:
        source: "acaisdk/acaisdk/configs-local.ini"
        target: "acaisdk/acaisdk/configs.ini"

    
    - name: Archive Release
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'release.zip'
        exclusions: '*.git* /*node_modules/* .*example*'

    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "acasdk.zip"
        token: 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
