name: Release ACAI SDK

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - main


jobs:
  archive-release:
  #timeout-minutes: 10 # timeout for the job
    name: Archive package and release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: First ls
      run: |
        ls
    - name: Second ls
      run: |
        ls /home/runner/work/acaisdk
    - name: Third ls
      run: |
        ls /home/runner/work/acaisdk/acaisdk
    - name: Fourth ls
      run: |
        ls /home/runner/work/acaisdk/acaisdk/acaisdk
    - name: Copy configs
      run: |
        cp /home/runner/work/acaisdk/acaisdk/acaisdk/configs-local.ini /home/runner/work/acaisdk/acaisdk/acaisdk/configs.ini 
        
    - name: Generate release tag
      uses: amitsingh-007/next-release-tag@v1.0.0
      with:
        github_token: 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
        
        
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: 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
      with:
        tag_name: ${{ env.release_tag }}
        release_name: Release-${{ env.release_tag }}
